build(docker): update git andd curl
Resolves

```
$ apk add --no-cache --update git=2.20.1-r0 curl=7.64.0-r3
 ---> Running in 94b5061dc5af
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  curl-7.66.0-r0:
    breaks: world[curl=7.64.0-r3]
  git-2.22.0-r0:
    breaks: world[git=2.20.1-r0]
```